CREATE TABLE `tpl1-1` (
  `ID` varchar(64) NOT NULL DEFAULT '',
  `Major_group` char(1) DEFAULT NULL,
  `Family` varchar(255) DEFAULT NULL,
  `Genus_hybrid_marker` char(1) DEFAULT NULL,
  `Genus` varchar(255) DEFAULT NULL,
  `Species_hybrid_marker` char(1) DEFAULT NULL,
  `Species` varchar(255) DEFAULT NULL,
  `Infraspecific_rank` varchar(32) DEFAULT NULL,
  `Infraspecific_epithet` varchar(255) DEFAULT NULL,
  `Authorship` varchar(255) DEFAULT NULL,
  `Taxonomic_status_in_TPL` varchar(32) DEFAULT NULL,
  `Nomenclatural_status_from_original_data_source` varchar(32) DEFAULT NULL,
  `Confidence_level` char(1) DEFAULT NULL,
  `Source` varchar(255) DEFAULT NULL,
  `Source_id` varchar(255) DEFAULT NULL,
  `IPNI_id` varchar(32) DEFAULT NULL,
  `Publication` varchar(255) DEFAULT NULL,
  `Collation` varchar(255) DEFAULT NULL,
  `Page` varchar(32) DEFAULT NULL,
  `Date` varchar(32) DEFAULT NULL,
  `AcceptedID` varchar(64) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `Family` (`Family`),
  KEY `Genus` (`Genus`),
  KEY `Species` (`Species`),
  KEY `Publication` (`Publication`),
  KEY `Collation` (`Collation`),
  KEY `Date` (`Date`),
  KEY `Major_group` (`Major_group`),
  KEY `Taxonomic_status_in_TPL` (`Taxonomic_status_in_TPL`),
  KEY `AcceptedID` (`AcceptedID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;